services:
  backend:
    image: backend_service
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
