package com.udea.siiuseguimproyectosback.domain.dto.project;

import lombok.Data;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Data Transfer Object (DTO) for Project Type.
 * <p>
 * This class is used to transfer project type data between the client
 * and server layers. It ensures that the name field is validated
 * to meet specific size and non-blank constraints.
 * </p>
 */
@Data
public class ProjectTypeDTO {

    /**
     * The unique identifier for the project type.
     * <ul>
     *  <li> This field represents the primary key of the Project Type entity. </li>
     *  <li> It is auto-generated by the database upon creation of a new record. </li>
     *  <li> The value is used to uniquely identify a project type in the system. </li>
     *  <li> It is included in the DTO to allow referencing and operations such as updates and deletes. </li>
     * </ul>
     * Constraints:
     * <ul>
     *  <li>Cannot be null when updating an existing project type.</li>
     * </ul>
     */
    @NotNull(message = "El identificador del tipo de proyecto no puede ser nulo.")
    private Long id;

    /**
     * The name of the project type.
     * <p>
     * Constraints:
     * <ul>
     *    <li>Must not be blank.</li>
     *    <li>Must have between 1 and 200 characters.</li>
     * </ul>
     * </p>
     */
    @NotBlank(message = "El nombre del tipo de proyecto no puede estar vacío.")
    @Size(min = 1, max = 200, message = "El nombre del tipo de proyecto debe tener entre 1 y 200 caracteres.")
    private String name;
}
